const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
try {
  require("dotenv").config({ path: ".env" });
} catch (e) {
  // dotenv may not be installed; using node --env-file flag or existing env vars
}

const AdminSchema = new mongoose.Schema({
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
});

const SettingSchema = new mongoose.Schema({
  companyName: String,
  tagline: String,
  subTagline: String,
  emails: [String],
  phones: [String],
  whatsapp: String,
  addresses: [
    {
      branchName: String,
      addressLine: String,
      cityState: String,
      phone: String,
      email: String,
      badge: String,
    },
  ],
  gst: String,
  iec: String,
  banker: String,
  socialLinks: { facebook: String, instagram: String, whatsapp: String },
  googleMapsEmbed: String,
  logoUrl: String,
  faviconUrl: String,
  footerDescription: String,
});

const CategorySchema = new mongoose.Schema({
  name: String,
  slug: String,
});

const ProductSchema = new mongoose.Schema({
  title: String,
  slug: String,
  category: String,
  description: String,
  shortDescription: String,
  images: [String],
  featuredImage: String,
  badge: String,
  badgeColor: String,
  specs: { type: Map, of: String },
  status: { type: String, default: "active" },
  featured: Boolean,
  productType: String,
  brand: String,
  subCategory: String,
  inquiryEnabled: Boolean,
  availableColors: mongoose.Schema.Types.Mixed,
  availableFinishes: mongoose.Schema.Types.Mixed,
  defaultColor: String,
  defaultFinish: String,
  customizationVariants: mongoose.Schema.Types.Mixed,
});

const TestimonialSchema = new mongoose.Schema({
  name: String,
  role: String,
  rating: Number,
  review: String,
  image: String,
  status: { type: String, default: "published" },
  displayOrder: Number,
});

const MONGODB_URI = process.env.MONGODB_URI;

if (!MONGODB_URI) {
  console.error("Error: MONGODB_URI is not defined in your environment variables (.env)");
  process.exit(1);
}

const Admin = mongoose.models.Admin || mongoose.model("Admin", AdminSchema);
const Setting = mongoose.models.Setting || mongoose.model("Setting", SettingSchema);
const Category = mongoose.models.Category || mongoose.model("Category", CategorySchema);
const Product = mongoose.models.Product || mongoose.model("Product", ProductSchema);
const Testimonial = mongoose.models.Testimonial || mongoose.model("Testimonial", TestimonialSchema);

async function seed() {
  await mongoose.connect(MONGODB_URI);
  console.log("Connected to MongoDB for seeding...");

  // 1. Seed admin
  const adminCount = await Admin.countDocuments();
  if (adminCount === 0) {
    const hashedPassword = await bcrypt.hash("admin12345", 10);
    await Admin.create({
      email: "admin@shivshakti.com",
      password: hashedPassword,
    });
    console.log("Seeded default admin account: admin@shivshakti.com / admin12345");
  } else {
    console.log("Admin accounts already exist. Skipping admin seed.");
  }

  // 2. Seed Settings
  const settingsCount = await Setting.countDocuments();
  if (settingsCount === 0) {
    await Setting.create({
      companyName: "Shivshakti Elevator Components Pvt. Ltd.",
      tagline: "Touch The Sky With Shivshakti",
      subTagline: "Work With Honesty",
      emails: ["sales.shivshakti22@gmail.com", "sales.shivshakti16@gmail.com"],
      phones: ["+91 9737171100", "+91 6352699700"],
      whatsapp: "+91 6352699700",
      addresses: [
        {
          branchName: "Surat Head Office",
          addressLine: "Plot No. 2, Hi-Tech Park, Siddharth Nagar Canal Road, Opp. Navin Florin, Vadod-Bhestan",
          cityState: "Surat - 395023, Gujarat, INDIA",
          phone: "+91 9737171100 / +91 6352699700",
          email: "sales.shivshakti22@gmail.com",
          badge: "Head Office",
        },
        {
          branchName: "Indore Branch",
          addressLine: "B 146 New Loha Mandi, Niranjanpur Devas Naka",
          cityState: "Indore - 452010, MP, INDIA",
          phone: "+91 9909801225",
          email: "sales.shivshaktiindore01@gmail.com",
          badge: "Branch Office",
        },
        {
          branchName: "Lucknow Branch",
          addressLine: "House No 11-A, 12-A Shyam Bhawan, Kanpur Road, Sarojini Nagar",
          cityState: "Lucknow - 226008, UP, INDIA",
          phone: "+91 6353 547 898",
          email: "sales.shivshaktilucknow@gmail.com",
          badge: "Branch Office",
        },
      ],
      gst: "24ACMFS0685B1Z7",
      iec: "5214013353",
      banker: "HDFC Bank",
      socialLinks: {
        facebook: "https://www.facebook.com/profile.php?id=100050285328348",
        instagram: "https://instagram.com/shiv_shakti_industries16",
        whatsapp: "https://api.whatsapp.com/send/?phone=6352699700",
      },
      googleMapsEmbed: "https://www.openstreetmap.org/export/embed.html?bbox=72.8289%2C21.1261%2C72.8389%2C21.1361&layer=mapnik&marker=21.131094%2C72.833979",
      logoUrl: "/images/logo.png",
      faviconUrl: "/favicon.ico",
      footerDescription: "Manufacturer of premium elevator cabins, automatic doors, car frames and components. Headquartered in Surat, Gujarat with branches in Indore and Lucknow.",
    });
    console.log("Seeded default settings.");
  } else {
    console.log("Settings already exist. Skipping settings seed.");
  }

  // 3. Seed Categories
  const categoryCount = await Category.countDocuments();
  if (categoryCount === 0) {
    await Category.insertMany([
      { name: "In-House", slug: "in-house" },
      { name: "Trading", slug: "trading" },
      { name: "Authorized Dealer", slug: "authorized" },
    ]);
    console.log("Seeded default categories.");
  } else {
    console.log("Categories already exist. Skipping categories seed.");
  }

  // 4. Seed Products
  console.log("Checking and seeding default products...");
  if (true) {
    const productsData = [
      // === MANUFACTURED DOORS ===
      {
        title: "Manual Door",
        slug: "manual-door",
        category: "door",
        badge: "In-House Made",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/manual-door.png",
        images: ["/images/products/manual-door.png"],
        galleryImages: ["/images/products/manual-door.png"],
        shortDescription: "Precision-engineered manual elevator doors manufactured in-house at our Surat facility. Available in SS and MS variants with premium finishing.",
        description: "Our manual elevator doors are manufactured with premium structural integrity, offering seamless operation, durability, and customization. Options include stainless steel hairline, gold mirror, and powder-coated mild steel.",
        fullDescription: "Our manual elevator doors are manufactured with premium structural integrity, offering seamless operation, durability, and customization. Options include stainless steel hairline, gold mirror, and powder-coated mild steel.",
        specs: {
          type: "Manual Sliding / Swing",
          material: "Stainless Steel / MS",
          finish: "Hairline / Mirror / Powder Coat",
        },
        specifications: {
          type: "Manual Sliding / Swing",
          material: "Stainless Steel / MS",
          finish: "Hairline / Mirror / Powder Coat",
        },
        featured: true,
        productType: "our-product",
        brand: "",
        subCategory: "Manual Doors",
        inquiryEnabled: true,
        highlights: ["In-house heavy-duty manufacturing", "Premium SS and MS options", "Custom color finishes available"],
        displayOrder: 1,
      },
      {
        title: "Automatic Door",
        slug: "automatic-door",
        category: "door",
        badge: "In-House Made",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/automatic-door.png",
        images: ["/images/products/automatic-door.png"],
        galleryImages: ["/images/products/automatic-door.png"],
        shortDescription: "Our flagship in-house automatic elevator doors with precision motor control, smooth operation, and premium finishes.",
        description: "Designed using advanced controller technology, these automatic doors offer silent opening, closing, and reliable safety measures. Ideal for commercial projects and luxury residential buildings.",
        fullDescription: "Designed using advanced controller technology, these automatic doors offer silent opening, closing, and reliable safety measures. Ideal for commercial projects and luxury residential buildings.",
        specs: {
          type: "Auto Sliding (Centre / Side Opening)",
          material: "Stainless Steel",
          finish: "Hairline / Satin / Mirror",
        },
        specifications: {
          type: "Auto Sliding (Centre / Side Opening)",
          material: "Stainless Steel",
          finish: "Hairline / Satin / Mirror",
        },
        featured: true,
        productType: "our-product",
        brand: "",
        subCategory: "Automatic Doors",
        inquiryEnabled: true,
        highlights: ["Silent motor drive system", "Advanced obstruction detection", "Durable hairline finish"],
        displayOrder: 2,
      },
      {
        title: "Glass Telescopic Door",
        slug: "glass-telescopic-door",
        category: "door",
        badge: "Premium Glass",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/automatic-door.png",
        images: ["/images/products/automatic-door.png"],
        galleryImages: ["/images/products/automatic-door.png"],
        shortDescription: "Telescopic automatic doors featuring high-clarity safety glass panels. Perfect for panoramic elevators and modern retail architectural designs.",
        description: "A compact telescopic opening mechanism crafted with structural tempered glass panels. Combines maximum opening width with full visibility.",
        fullDescription: "A compact telescopic opening mechanism crafted with structural tempered glass panels. Combines maximum opening width with full visibility.",
        specs: {
          type: "Telescopic Opening",
          glass: "10mm Tempered Safety Glass",
          frame: "Stainless Steel Bordered",
        },
        specifications: {
          type: "Telescopic Opening",
          glass: "10mm Tempered Safety Glass",
          frame: "Stainless Steel Bordered",
        },
        featured: false,
        productType: "our-product",
        brand: "",
        subCategory: "Telescopic Doors",
        inquiryEnabled: true,
        highlights: ["Panoramic aesthetic styling", "High strength safety glass", "Space-saving telescopic design"],
        displayOrder: 3,
      },
      {
        title: "Center Opening Premium Door",
        slug: "center-opening-premium-door",
        category: "door",
        badge: "Luxury Model",
        badgeColor: "brand-orange",
        featuredImage: "/images/products/manual-door.png",
        images: ["/images/products/manual-door.png"],
        galleryImages: ["/images/products/manual-door.png"],
        shortDescription: "Elegant center-opening automatic doors with premium gold mirror plating and custom etched patterns for luxury building lobbies.",
        description: "Our luxury center-opening doors feature structural vibration-damping sheets and premium gold PVD coatings. Highly recommended for commercial skyscrapers and premium residences.",
        fullDescription: "Our luxury center-opening doors feature structural vibration-damping sheets and premium gold PVD coatings. Highly recommended for commercial skyscrapers and premium residences.",
        specs: {
          type: "Center Opening Auto Door",
          finish: "Gold Mirror PVD Coated",
          cladding: "Etched Architectural Pattern",
        },
        specifications: {
          type: "Center Opening Auto Door",
          finish: "Gold Mirror PVD Coated",
          cladding: "Etched Architectural Pattern",
        },
        featured: false,
        productType: "our-product",
        brand: "",
        subCategory: "Center Opening Doors",
        inquiryEnabled: true,
        highlights: ["Elegant gold-mirror finish", "Custom structural vibration-damping", "Quiet high-speed opening"],
        displayOrder: 4,
      },

      // === MANUFACTURED CABINS ===
      {
        title: "Shivshakti Premium Layout Cabin",
        slug: "shivshakti-premium-layout-cabin",
        category: "layout-cabin",
        badge: "Configurator",
        badgeColor: "brand-orange",
        featuredImage: "/images/products/ss-cabin.png",
        images: ["/images/products/ss-cabin.png"],
        galleryImages: ["/images/products/ss-cabin.png"],
        shortDescription: "Interactive, fully customizable luxury layout cabin. Choose colors and finishes in real time to preview premium aesthetic options.",
        description: "Shivshakti premium layout cabins support advanced customization. Configure between Dark Grey, Gold, and Rose Gold colors in Mirror or Hairline finishes. Our Surat factory manufactures bespoke designs using high grade stainless steel and premium materials.",
        fullDescription: "Shivshakti premium layout cabins support advanced customization. Configure between Dark Grey, Gold, and Rose Gold colors in Mirror or Hairline finishes. Our Surat factory manufactures bespoke designs using high grade stainless steel and premium materials.",
        specs: {
          type: "Luxury Passenger Cabin",
          material: "SS 304 Grade",
          lighting: "Integrated LED ceiling panel",
        },
        specifications: {
          type: "Luxury Passenger Cabin",
          material: "SS 304 Grade",
          lighting: "Integrated LED ceiling panel",
        },
        featured: true,
        productType: "our-product",
        brand: "",
        subCategory: "Layout Cabins",
        inquiryEnabled: true,
        highlights: ["Real-time visual customization", "Premium HSL PVD colors", "Surat factory direct production"],
        displayOrder: 4,
        availableColors: [
          { name: "Dark Grey", code: "#4B5563", enabled: true },
          { name: "Gold", code: "#D4AF37", enabled: true },
          { name: "Rose Gold", code: "#B76E79", enabled: true },
        ],
        availableFinishes: [
          { name: "Mirror", code: "mirror", enabled: true },
          { name: "Hairline", code: "hairline", enabled: true },
        ],
        defaultColor: "Dark Grey",
        defaultFinish: "Mirror",
        customizationVariants: [
          { color: "Dark Grey", finish: "Mirror", image: "/images/products/ss-cabin.png", enabled: true },
          { color: "Dark Grey", finish: "Hairline", image: "/images/products/ss-cabin.png", enabled: true },
          { color: "Gold", finish: "Mirror", image: "/images/products/ss-cabin.png", enabled: true },
          { color: "Gold", finish: "Hairline", image: "/images/products/ss-cabin.png", enabled: true },
          { color: "Rose Gold", finish: "Mirror", image: "/images/products/ss-cabin.png", enabled: true },
          { color: "Rose Gold", finish: "Hairline", image: "/images/products/ss-cabin.png", enabled: true },
        ]
      },
      {
        title: "SS / MS Cabin",
        slug: "ss-ms-cabin",
        category: "cabin",
        badge: "In-House Made",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/ss-cabin.png",
        images: ["/images/products/ss-cabin.png"],
        galleryImages: ["/images/products/ss-cabin.png"],
        shortDescription: "Fully customizable elevator cabins in Stainless Steel and Mild Steel. Manufactured at our 40,000 sq ft Surat facility.",
        description: "Shivshakti cabins set the standard for luxury. Engineered with acoustic insulation, premium lighting layouts, ceiling designs, and customized wall panels in multiple architectural finishes.",
        fullDescription: "Shivshakti cabins set the standard for luxury. Engineered with acoustic insulation, premium lighting layouts, ceiling designs, and customized wall panels in multiple architectural finishes.",
        specs: {
          type: "Passenger / Goods / Hospital",
          material: "SS 304 / MS",
          finish: "Multiple Panel Options Available",
        },
        specifications: {
          type: "Passenger / Goods / Hospital",
          material: "SS 304 / MS",
          finish: "Multiple Panel Options Available",
        },
        featured: true,
        productType: "our-product",
        brand: "",
        subCategory: "SS Cabins",
        inquiryEnabled: true,
        highlights: ["Acoustic wall insulation", "Integrated LED ceiling panel", "Surat factory direct production"],
        displayOrder: 5,
      },
      {
        title: "Panoramic Glass Cabin",
        slug: "panoramic-glass-cabin",
        category: "cabin",
        badge: "Luxury View",
        badgeColor: "brand-orange",
        featuredImage: "/images/products/ss-cabin.png",
        images: ["/images/products/ss-cabin.png"],
        galleryImages: ["/images/products/ss-cabin.png"],
        shortDescription: "Spectacular glass elevator cabins designed for high-rise shopping malls, hotels, and futuristic modern corporate headquarters.",
        description: "Features a full 180-degree field of view using custom-curved laminated safety glass. Comes with premium under-floor structural steel supports and stainless steel columns.",
        fullDescription: "Features a full 180-degree field of view using custom-curved laminated safety glass. Comes with premium under-floor structural steel supports and stainless steel columns.",
        specs: {
          type: "Panoramic Capsule Cabin",
          glass: "12mm Curved Laminated Safety Glass",
          lighting: "Indirect RGB LED Lighting System",
        },
        specifications: {
          type: "Panoramic Capsule Cabin",
          glass: "12mm Curved Laminated Safety Glass",
          lighting: "Indirect RGB LED Lighting System",
        },
        featured: false,
        productType: "our-product",
        brand: "",
        subCategory: "Glass Cabins",
        inquiryEnabled: true,
        highlights: ["180-degree field of view", "High strength curved glass panels", "Premium stainless steel accents"],
        displayOrder: 6,
      },
      {
        title: "Luxury Designer Cabin",
        slug: "luxury-designer-cabin",
        category: "cabin",
        badge: "Elite Series",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/ss-cabin.png",
        images: ["/images/products/ss-cabin.png"],
        galleryImages: ["/images/products/ss-cabin.png"],
        shortDescription: "Custom luxury cabins with gold finish, premium mirror panels, and architectural stone flooring. Designed for elite residencies.",
        description: "Crafted for prestigious developments. Features gold mirror stainless steel accents, warm mood lighting, textured leather panels, and absolute marble floor tiling.",
        fullDescription: "Crafted for prestigious developments. Features gold mirror stainless steel accents, warm mood lighting, textured leather panels, and absolute marble floor tiling.",
        specs: {
          type: "Ultra-Luxury Passenger Cabin",
          cladding: "Gold Mirror SS & Leather Panel",
          flooring: "Imported Italian Marble",
        },
        specifications: {
          type: "Ultra-Luxury Passenger Cabin",
          cladding: "Gold Mirror SS & Leather Panel",
          flooring: "Imported Italian Marble",
        },
        featured: false,
        productType: "our-product",
        brand: "",
        subCategory: "Designer Cabins",
        inquiryEnabled: true,
        highlights: ["Imported marble floor tiles", "Gold PVD titanium accents", "Acoustically isolated structure"],
        displayOrder: 7,
      },
      {
        title: "Commercial Passenger Cabin",
        slug: "commercial-passenger-cabin",
        category: "cabin",
        badge: "Heavy Duty",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/ss-cabin.png",
        images: ["/images/products/ss-cabin.png"],
        galleryImages: ["/images/products/ss-cabin.png"],
        shortDescription: "Sturdy and modern passenger cabins optimized for high-traffic commercial office blocks and municipal buildings.",
        description: "Built with high-density anti-scratch stainless steel panels. Resilient, easy to clean, and fully compliant with ADA and fire safety regulations.",
        fullDescription: "Built with high-density anti-scratch stainless steel panels. Resilient, easy to clean, and fully compliant with ADA and fire safety regulations.",
        specs: {
          type: "Commercial Passenger",
          material: "Scratch-Resistant SS 304",
          handrail: "Dual Stainless Steel Handrails",
        },
        specifications: {
          type: "Commercial Passenger",
          material: "Scratch-Resistant SS 304",
          handrail: "Dual Stainless Steel Handrails",
        },
        featured: false,
        productType: "our-product",
        brand: "",
        subCategory: "SS Cabins",
        inquiryEnabled: true,
        highlights: ["ADA compliant layouts", "Scratch-resistant SS panels", "Dual impact-proof handrails"],
        displayOrder: 8,
      },

      // === MANUFACTURED FRAMES ===
      {
        title: "Elevator Car Frame",
        slug: "car-frame",
        category: "frame",
        badge: "In-House Made",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/car-frame.png",
        images: ["/images/products/car-frame.png"],
        galleryImages: ["/images/products/car-frame.png"],
        shortDescription: "Structural elevator car frames engineered for load capacity and safety. Compatible with all major drive systems.",
        description: "Engineered specifically to minimize vibration and cabin sway. We use structural steel members welded under strict quality conditions to ensure maximum lifespan.",
        fullDescription: "Engineered specifically to minimize vibration and cabin sway. We use structural steel members welded under strict quality conditions to ensure maximum lifespan.",
        specs: {
          type: "Standard / Heavy Duty",
          material: "Structural Steel",
          finish: "Powder Coated",
        },
        specifications: {
          type: "Standard / Heavy Duty",
          material: "Structural Steel",
          finish: "Powder Coated",
        },
        featured: true,
        productType: "our-product",
        brand: "",
        subCategory: "Door Frames",
        inquiryEnabled: true,
        highlights: ["Vibration-damped structural steel", "Precision alignments", "Universal drive compatibility"],
        displayOrder: 9,
      },
      {
        title: "Counterweight Frame",
        slug: "counterweight-frame",
        category: "frame",
        badge: "In-House Made",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/car-frame.png",
        images: ["/images/products/car-frame.png"],
        galleryImages: ["/images/products/car-frame.png"],
        shortDescription: "Sturdy counterweight frames designed for modular cast iron or concrete filler blocks. High structural durability.",
        description: "Engineered to handle rapid acceleration cycles. Equipped with safety guide shoes and guide rail brackets, manufactured to withstand demanding commercial lift setups.",
        fullDescription: "Engineered to handle rapid acceleration cycles. Equipped with safety guide shoes and guide rail brackets, manufactured to withstand demanding commercial lift setups.",
        specs: {
          type: "Modular Counterweight Frame",
          capacity: "Up to 2500 kg",
          material: "Heavy Gauge Welded Steel Channel",
        },
        specifications: {
          type: "Modular Counterweight Frame",
          capacity: "Up to 2500 kg",
          material: "Heavy Gauge Welded Steel Channel",
        },
        featured: false,
        productType: "our-product",
        brand: "",
        subCategory: "Special Frames",
        inquiryEnabled: true,
        highlights: ["Heavy-gauge welded steel", "Equipped with safety guide shoes", "Optimized weight distribution layout"],
        displayOrder: 10,
      },
      {
        title: "Telescopic Door Frame",
        slug: "telescopic-door-frame",
        category: "frame",
        badge: "In-House Made",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/car-frame.png",
        images: ["/images/products/car-frame.png"],
        galleryImages: ["/images/products/car-frame.png"],
        shortDescription: "Specialized door frames designed to support telescopic sliding door headers and tracks. Simplifies alignment during installation.",
        description: "Built to match tight architectural tolerances. Made with high-strength structural profiles that prevent door tracks from warping or misaligning over years of service.",
        fullDescription: "Built to match tight architectural tolerances. Made with high-strength structural profiles that prevent door tracks from warping or misaligning over years of service.",
        specs: {
          type: "Telescopic Interface Frame",
          alignment: "Self-Aligning Mount Brackets",
          material: "Reinforced Galvanized Steel",
        },
        specifications: {
          type: "Telescopic Interface Frame",
          alignment: "Self-Aligning Mount Brackets",
          material: "Reinforced Galvanized Steel",
        },
        featured: false,
        productType: "our-product",
        brand: "",
        subCategory: "Door Frames",
        inquiryEnabled: true,
        highlights: ["Galvanized structural steel", "Self-aligning bracket points", "Anti-warp rigid profile design"],
        displayOrder: 11,
      },
      {
        title: "Heavy Duty Machine Frame",
        slug: "heavy-duty-machine-frame",
        category: "frame",
        badge: "In-House Made",
        badgeColor: "brand-orange",
        featuredImage: "/images/products/car-frame.png",
        images: ["/images/products/car-frame.png"],
        galleryImages: ["/images/products/car-frame.png"],
        shortDescription: "Heavy structural steel frames designed to support geared/gearless drive machines in overhead or basement layouts.",
        description: "Crafted from heavy-duty structural I-beams. Supports machine weight and torque load, fully dynamic-load certified with vibration damping pads included.",
        fullDescription: "Crafted from heavy-duty structural I-beams. Supports machine weight and torque load, fully dynamic-load certified with vibration damping pads included.",
        specs: {
          type: "Overhead Machine Bed Frame",
          loadLimit: "Up to 8000 kg",
          beams: "Heavy Duty I-Beams",
        },
        specifications: {
          type: "Overhead Machine Bed Frame",
          loadLimit: "Up to 8000 kg",
          beams: "Heavy Duty I-Beams",
        },
        featured: false,
        productType: "our-product",
        brand: "",
        subCategory: "Special Frames",
        inquiryEnabled: true,
        highlights: ["Heavy I-beam steel framework", "Vibration damping isolation pads", "Fully dynamic load certified"],
        displayOrder: 12,
      },

      // === AUTHORIZED DEALER: MONTANARI ===
      {
        title: "Geared Traction Machine",
        slug: "montanari-geared-machine",
        category: "Safety Components",
        badge: "Montanari Authorized",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/machine.png",
        images: ["/images/products/machine.png"],
        galleryImages: ["/images/products/machine.png"],
        shortDescription: "Premium geared traction machines sourced from Montanari. Highly reliable drive systems for high-traffic passenger lifts.",
        description: "Classic traction machine featuring superior worm gear engineering and quiet operation. Sourced directly from Montanari, Italy.",
        fullDescription: "Classic traction machine featuring superior worm gear engineering and quiet operation. Sourced directly from Montanari, Italy.",
        specs: {
          type: "Geared Traction Drive",
          capacity: "Up to 1600 kg",
          origin: "Montanari (Italy)",
        },
        specifications: {
          type: "Geared Traction Drive",
          capacity: "Up to 1600 kg",
          origin: "Montanari (Italy)",
        },
        featured: false,
        productType: "dealer-product",
        brand: "Montanari",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Italian engineering quality", "High worm gear efficiency", "Low vibration operation"],
        displayOrder: 13,
      },
      {
        title: "Gearless Traction Machine G200",
        slug: "montanari-gearless-g200",
        category: "Safety Components",
        badge: "Montanari Dealer",
        badgeColor: "brand-orange",
        featuredImage: "/images/products/machine.png",
        images: ["/images/products/machine.png"],
        galleryImages: ["/images/products/machine.png"],
        shortDescription: "Ultra-compact Montanari gearless machine G200. Designed for modern machine room-less (MRL) high-speed elevator layouts.",
        description: "The G200 drive uses high-density permanent magnet synchronous motors. Provides ultimate efficiency and absolute smoothness during travel.",
        fullDescription: "The G200 drive uses high-density permanent magnet synchronous motors. Provides ultimate efficiency and absolute smoothness during travel.",
        specs: {
          type: "Gearless PM Drive",
          capacity: "Up to 1000 kg",
          speed: "Up to 1.75 m/s",
        },
        specifications: {
          type: "Gearless PM Drive",
          capacity: "Up to 1000 kg",
          speed: "Up to 1.75 m/s",
        },
        featured: true,
        productType: "dealer-product",
        brand: "Montanari",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Synchronous permanent magnet motor", "Compact footprint for MRL", "High energy savings profile"],
        displayOrder: 14,
      },
      {
        title: "Gearless Machine G300",
        slug: "montanari-gearless-g300",
        category: "Safety Components",
        badge: "Montanari Dealer",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/machine.png",
        images: ["/images/products/machine.png"],
        galleryImages: ["/images/products/machine.png"],
        shortDescription: "High-capacity gearless machine G300. Ideal for heavy-duty commercial passenger lifts and stretcher elevators.",
        description: "Heavy-duty gearless synchronous motor for high-capacity applications. Delivers reliable performance with low maintenance cycles.",
        fullDescription: "Heavy-duty gearless synchronous motor for high-capacity applications. Delivers reliable performance with low maintenance cycles.",
        specs: {
          type: "High Capacity Gearless",
          capacity: "Up to 2000 kg",
          pulley: "320mm hardened steel",
        },
        specifications: {
          type: "High Capacity Gearless",
          capacity: "Up to 2000 kg",
          pulley: "320mm hardened steel",
        },
        featured: false,
        productType: "dealer-product",
        brand: "Montanari",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Heavy load rating up to 2000kg", "Large hardened steel traction sheave", "Low heat dissipation design"],
        displayOrder: 15,
      },
      {
        title: "Montanari M73 Geared Drive",
        slug: "montanari-m73-geared",
        category: "Safety Components",
        badge: "Montanari Gear",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/machine.png",
        images: ["/images/products/machine.png"],
        galleryImages: ["/images/products/machine.png"],
        shortDescription: "Classic Montanari M73 geared drive machine. The industry standard for reliable low-to-mid rise passenger lifts.",
        description: "The M73 series geared machine is built for robustness. Known worldwide for long service life, low oil wear, and simple field serviceability.",
        fullDescription: "The M73 series geared machine is built for robustness. Known worldwide for long service life, low oil wear, and simple field serviceability.",
        specs: {
          type: "Geared Traction Drive",
          loadCapacity: "Up to 630 kg",
          ratio: "1/45 traction ratio",
        },
        specifications: {
          type: "Geared Traction Drive",
          loadCapacity: "Up to 630 kg",
          ratio: "1/45 traction ratio",
        },
        featured: false,
        productType: "dealer-product",
        brand: "Montanari",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Extremely long service lifespan", "Industry standard replacement parts", "Low oil degradation rate"],
        displayOrder: 16,
      },

      // === AUTHORIZED DEALER: MONARCH ===
      {
        title: "Monarch NICE 3000+ Controller",
        slug: "monarch-nice-3000-controller",
        category: "Controllers",
        badge: "Monarch Authorized",
        badgeColor: "brand-orange",
        featuredImage: "/images/products/lop-cop.png",
        images: ["/images/products/lop-cop.png"],
        galleryImages: ["/images/products/lop-cop.png"],
        shortDescription: "Monarch NICE 3000+ integrated controller. The market-leading choice for intelligent elevator control systems.",
        description: "Combines variable frequency drive control with elevator logic in a single microprocessor. Highly programmable and dynamic.",
        fullDescription: "Combines variable frequency drive control with elevator logic in a single microprocessor. Highly programmable and dynamic.",
        specs: {
          type: "Integrated Controller/Drive",
          processor: "Dual core DSP microcontroller",
          compatibility: "Geared / Gearless Motors",
        },
        specifications: {
          type: "Integrated Controller/Drive",
          processor: "Dual core DSP microcontroller",
          compatibility: "Geared / Gearless Motors",
        },
        featured: true,
        productType: "dealer-product",
        brand: "Monarch",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Dual core digital signal processor", "Logic & motor drive in one system", "Wide tuning parameters"],
        displayOrder: 17,
      },
      {
        title: "Monarch NICE 1000+ Integrated Drive",
        slug: "monarch-nice-1000-drive",
        category: "Controllers",
        badge: "Monarch Dealer",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/lop-cop.png",
        images: ["/images/products/lop-cop.png"],
        galleryImages: ["/images/products/lop-cop.png"],
        shortDescription: "Integrated controller and drive solution optimized for low-to-medium rise residential installations.",
        description: "Monarch's cost-effective integrated drive solution. Delivers smooth acceleration ramps, direct leveling, and standard diagnostic tools.",
        fullDescription: "Monarch's cost-effective integrated drive solution. Delivers smooth acceleration ramps, direct leveling, and standard diagnostic tools.",
        specs: {
          type: "Integrated Residential Controller",
          capacity: "Up to 5.5 kW / 7.5 kW",
          leveling: "Direct landing control",
        },
        specifications: {
          type: "Integrated Residential Controller",
          capacity: "Up to 5.5 kW / 7.5 kW",
          leveling: "Direct landing control",
        },
        featured: false,
        productType: "dealer-product",
        brand: "Monarch",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Residential system optimization", "Smooth acceleration curving", "Cost-effective direct landing"],
        displayOrder: 18,
      },
      {
        title: "Premium LOP Digital Display",
        slug: "monarch-lop-panel",
        category: "Controllers",
        badge: "Monarch Accessories",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/lop-cop.png",
        images: ["/images/products/lop-cop.png"],
        galleryImages: ["/images/products/lop-cop.png"],
        shortDescription: "Landing Operating Panel (LOP) featuring high brightness dot matrix and segment displays. Sourced from Monarch.",
        description: "Equipped with micro-travel push buttons and clear floor positioning indicators. Matches structural wall frames.",
        fullDescription: "Equipped with micro-travel push buttons and clear floor positioning indicators. Matches structural wall frames.",
        specs: {
          type: "Wall Mount LOP",
          display: "Red LED Dot Matrix",
          interface: "Tactile micro-travel buttons",
        },
        specifications: {
          type: "Wall Mount LOP",
          display: "Red LED Dot Matrix",
          interface: "Tactile micro-travel buttons",
        },
        featured: false,
        productType: "dealer-product",
        brand: "Monarch",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["High-brightness red segment LED", "Micro-travel feedback buttons", "Brushed metal wall framing"],
        displayOrder: 19,
      },
      {
        title: "Touch Glass COP Panel",
        slug: "monarch-cop-panel",
        category: "Controllers",
        badge: "Monarch Custom",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/lop-cop.png",
        images: ["/images/products/lop-cop.png"],
        galleryImages: ["/images/products/lop-cop.png"],
        shortDescription: "Car Operating Panel (COP) featuring premium black tempered glass panels and full-height touch buttons.",
        description: "A luxury upgrade for cabins. Provides soft backlighting, integrated intercom layout, emergency key switch area, and digital TFT indicator screen.",
        fullDescription: "A luxury upgrade for cabins. Provides soft backlighting, integrated intercom layout, emergency key switch area, and digital TFT indicator screen.",
        specs: {
          type: "Flush Cabin COP",
          panel: "Black Tempered Glass Faceplate",
          display: "7-inch Color TFT Media Display",
        },
        specifications: {
          type: "Flush Cabin COP",
          panel: "Black Tempered Glass Faceplate",
          display: "7-inch Color TFT Media Display",
        },
        featured: false,
        productType: "dealer-product",
        brand: "Monarch",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Tempered glass capacitive touch", "Full color 7-inch media screen", "Integrated speaker intercom grille"],
        displayOrder: 20,
      },

      // === AUTHORIZED DEALER: SAVERA ===
      {
        title: "T-Guide Rail T89",
        slug: "savera-t89-guide-rail",
        category: "Accessories",
        badge: "Savera Authorized",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/guide-rail.png",
        images: ["/images/products/guide-rail.png"],
        galleryImages: ["/images/products/guide-rail.png"],
        shortDescription: "Savera T89 cold-drawn T-guide rails. Ensures straightness and safety for passenger elevator carriages.",
        description: "Precision-straightened steel rails manufactured under strict thickness control. Sourced directly from Savera's manufacturing lines.",
        fullDescription: "Precision-straightened steel rails manufactured under strict thickness control. Sourced directly from Savera's manufacturing lines.",
        specs: {
          type: "T-Guide Rail",
          size: "T89/B (89mm x 62mm x 16mm)",
          process: "Cold Drawn Steel",
        },
        specifications: {
          type: "T-Guide Rail",
          size: "T89/B (89mm x 62mm x 16mm)",
          process: "Cold Drawn Steel",
        },
        featured: false,
        productType: "dealer-product",
        brand: "Savera",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Strict straightness tolerances", "Cold-drawn structural profile", "Savera verified certification"],
        displayOrder: 21,
      },
      {
        title: "Guide Rail Bracket Assembly",
        slug: "savera-bracket-assembly",
        category: "Accessories",
        badge: "Savera Bracket",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/guide-rail.png",
        images: ["/images/products/guide-rail.png"],
        galleryImages: ["/images/products/guide-rail.png"],
        shortDescription: "Heavy-duty guide rail mounting brackets designed to anchor Savera rails to concrete or brick shaft walls.",
        description: "Adjustable steel brackets that allow for fine leveling of guide rails. Provides heavy-duty load support and dampens guide rail vibrations.",
        fullDescription: "Adjustable steel brackets that allow for fine leveling of guide rails. Provides heavy-duty load support and dampens guide rail vibrations.",
        specs: {
          type: "Adjustable Rail Bracket",
          finish: "Zinc Plated / Anti-rust coating",
          adjustmentRange: "Up to 50mm dynamic range",
        },
        specifications: {
          type: "Adjustable Rail Bracket",
          finish: "Zinc Plated / Anti-rust coating",
          adjustmentRange: "Up to 50mm dynamic range",
        },
        featured: false,
        productType: "dealer-product",
        brand: "Savera",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Heavy zinc anti-rust plating", "Adjustable bracket alignment range", "Vibration isolators pre-integrated"],
        displayOrder: 22,
      },
      {
        title: "Savera Cold Drawn Guide Rail",
        slug: "savera-cold-drawn-rail",
        category: "Accessories",
        badge: "Savera Rails",
        badgeColor: "brand-orange",
        featuredImage: "/images/products/guide-rail.png",
        images: ["/images/products/guide-rail.png"],
        galleryImages: ["/images/products/guide-rail.png"],
        shortDescription: "Savera premium cold-drawn guide rails for low-to-mid speed residential lifts. Delivers quiet operation.",
        description: "Specialized cold-drawn guide rails optimized for residential lifts. Provides smooth guides and reduces guide shoe wear.",
        fullDescription: "Specialized cold-drawn guide rails optimized for residential lifts. Provides smooth guides and reduces guide shoe wear.",
        specs: {
          type: "Cold Drawn Guide Rail",
          sizing: "T70/B (70mm wide base)",
          straightness: "0.1mm tolerance standard",
        },
        specifications: {
          type: "Cold Drawn Guide Rail",
          sizing: "T70/B (70mm wide base)",
          straightness: "0.1mm tolerance standard",
        },
        featured: true,
        productType: "dealer-product",
        brand: "Savera",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Ultra-quiet residential tracking", "Minimal guide shoe friction wear", "Precision base tolerances"],
        displayOrder: 23,
      },
      {
        title: "Savera High-Speed Guide Shoe",
        slug: "savera-guide-shoe",
        category: "Accessories",
        badge: "Savera Accessories",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/guide-rail.png",
        images: ["/images/products/guide-rail.png"],
        galleryImages: ["/images/products/guide-rail.png"],
        shortDescription: "Sliding guide shoes with replaceable nylon liners. Ensures stable cabin movement on T-guide rails.",
        description: "Nylon insert guide shoes designed to slide smoothly along guide rails. Reduces cabin roll and pitch while traveling.",
        fullDescription: "Nylon insert guide shoes designed to slide smoothly along guide rails. Reduces cabin roll and pitch while traveling.",
        specs: {
          type: "Sliding Guide Shoe",
          insert: "High Density Self-Lubricating Nylon",
          casing: "Cast Iron Base",
        },
        specifications: {
          type: "Sliding Guide Shoe",
          insert: "High Density Self-Lubricating Nylon",
          casing: "Cast Iron Base",
        },
        featured: false,
        productType: "dealer-product",
        brand: "Savera",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Replaceable self-lubricating nylon liners", "Heavy cast-iron base shell", "Reduces carriage roll and sway"],
        displayOrder: 24,
      },

      // === AUTHORIZED DEALER: USHA MARTIN ===
      {
        title: "Usha Martin 8mm Wire Rope",
        slug: "usha-martin-8mm-rope",
        category: "Safety Components",
        badge: "Usha Martin Dealer",
        badgeColor: "brand-orange",
        featuredImage: "/images/products/wire-rope.png",
        images: ["/images/products/wire-rope.png"],
        galleryImages: ["/images/products/wire-rope.png"],
        shortDescription: "Certified 8mm traction wire rope manufactured by Usha Martin. Designed for high fatigue lift cycles.",
        description: "Optimized for traction drives. Boasts high resistance to core breakage and minimal diameter degradation over years of service.",
        fullDescription: "Optimized for traction drives. Boasts high resistance to core breakage and minimal diameter degradation over years of service.",
        specs: {
          brand: "Usha Martin",
          diameter: "8.0 mm nominal",
          lay: "Right Regular Lay (RRL)",
        },
        specifications: {
          brand: "Usha Martin",
          diameter: "8.0 mm nominal",
          lay: "Right Regular Lay (RRL)",
        },
        featured: true,
        productType: "dealer-product",
        brand: "Usha Martin",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["High cyclic fatigue resistance", "Minimal diameter degradation", "Right regular lay standard"],
        displayOrder: 25,
      },
      {
        title: "Usha Martin 10mm Wire Rope",
        slug: "usha-martin-10mm-rope",
        category: "Safety Components",
        badge: "Usha Martin Dealer",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/wire-rope.png",
        images: ["/images/products/wire-rope.png"],
        galleryImages: ["/images/products/wire-rope.png"],
        shortDescription: "Premium 10mm steel core traction wire rope from Usha Martin. Best for medium-duty passenger lifts.",
        description: "Heavy-duty 10mm traction rope. Features parallel-laid inner wires for high surface contact, reducing traction sheave wear.",
        fullDescription: "Heavy-duty 10mm traction rope. Features parallel-laid inner wires for high surface contact, reducing traction sheave wear.",
        specs: {
          brand: "Usha Martin",
          diameter: "10.0 mm nominal",
          core: "Independent Wire Rope Core (IWRC)",
        },
        specifications: {
          brand: "Usha Martin",
          diameter: "10.0 mm nominal",
          core: "Independent Wire Rope Core (IWRC)",
        },
        featured: false,
        productType: "dealer-product",
        brand: "Usha Martin",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Independent wire rope core (IWRC)", "Reduced traction sheave wear", "Direct OEM factory certification"],
        displayOrder: 26,
      },
      {
        title: "Usha Martin 12mm Wire Rope",
        slug: "usha-martin-12mm-rope",
        category: "Safety Components",
        badge: "Usha Martin Dealer",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/wire-rope.png",
        images: ["/images/products/wire-rope.png"],
        galleryImages: ["/images/products/wire-rope.png"],
        shortDescription: "Certified 12mm high-tensile wire rope from Usha Martin. Sourced for commercial passenger elevators.",
        description: "High breaking load 12mm wire rope. Recommended for high rise installations and high-occupancy office building lifts.",
        fullDescription: "High breaking load 12mm wire rope. Recommended for high rise installations and high-occupancy office building lifts.",
        specs: {
          brand: "Usha Martin",
          diameter: "12.0 mm nominal",
          grade: "1770 N/mm2 tensile strength",
        },
        specifications: {
          brand: "Usha Martin",
          diameter: "12.0 mm nominal",
          grade: "1770 N/mm2 tensile strength",
        },
        featured: false,
        productType: "dealer-product",
        brand: "Usha Martin",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["1770 N/mm2 high-tensile grade", "Ideal for high-occupancy commercial lifts", "Optimized structural elasticity"],
        displayOrder: 27,
      },
      {
        title: "Usha Martin 16mm Wire Rope",
        slug: "usha-martin-16mm-rope",
        category: "Safety Components",
        badge: "Usha Martin Heavy",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/wire-rope.png",
        images: ["/images/products/wire-rope.png"],
        galleryImages: ["/images/products/wire-rope.png"],
        shortDescription: "Heavy-duty 16mm steel suspension wire rope from Usha Martin. Designed for high capacity cargo elevators.",
        description: "The ultimate capacity wire rope in the Usha Martin catalog. Built to withstand extreme load conditions and rough industrial environments.",
        fullDescription: "The ultimate capacity wire rope in the Usha Martin catalog. Built to withstand extreme load conditions and rough industrial environments.",
        specs: {
          brand: "Usha Martin",
          diameter: "16.0 mm nominal",
          breakingLoad: "154 kN minimum breaking load",
        },
        specifications: {
          brand: "Usha Martin",
          diameter: "16.0 mm nominal",
          breakingLoad: "154 kN minimum breaking load",
        },
        featured: false,
        productType: "dealer-product",
        brand: "Usha Martin",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Industrial freight lift certified", "Extreme 154 kN minimum breaking load", "High wear resistance core cladding"],
        displayOrder: 28,
      },

      // === FULL ELEVATOR KITS ===
      {
        title: "MRL Traction Elevator Kit",
        slug: "mrl-traction-kit",
        category: "elevator-kit",
        badge: "Full Kit",
        badgeColor: "brand-orange",
        featuredImage: "/images/products/mrl-kit.png",
        images: ["/images/products/mrl-kit.png"],
        galleryImages: ["/images/products/mrl-kit.png"],
        shortDescription: "Complete Machine Room-Less (MRL) elevator solution. Fully integrated components for space-saving layouts.",
        description: "Complete Machine Room-Less (MRL) elevator solution. Fully integrated components for space-saving layouts, quiet operations, and high efficiency.",
        fullDescription: "Complete Machine Room-Less (MRL) elevator solution. Fully integrated components for space-saving layouts, quiet operations, and high efficiency.",
        specs: {
          drive: "Gearless Permanent Magnet Motor",
          control: "Monarch Integrated NICE 3000+",
          speed: "1.0 m/s to 1.75 m/s",
        },
        specifications: {
          drive: "Gearless Permanent Magnet Motor",
          control: "Monarch Integrated NICE 3000+",
          speed: "1.0 m/s to 1.75 m/s",
        },
        featured: true,
        productType: "elevator-kit",
        brand: "",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["No machine room required", "Saves up to 40% floor space", "Equipped with permanent magnet drives"],
        displayOrder: 29,
      },
      {
        title: "Hydraulic Luxury Villa Lift Kit",
        slug: "hydraulic-villa-kit",
        category: "elevator-kit",
        badge: "Premium Kit",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/hydraulic-kit.png",
        images: ["/images/products/hydraulic-kit.png"],
        galleryImages: ["/images/products/hydraulic-kit.png"],
        shortDescription: "Premium hydraulic villa lift kit. Designed for low-rise vertical transit with luxurious interior designs.",
        description: "Ultra-premium hydraulic villa lift kit. Designed for low-to-medium rise vertical transit, featuring custom luxurious interior designs and quiet operation.",
        fullDescription: "Ultra-premium hydraulic villa lift kit. Designed for low-to-medium rise vertical transit, featuring custom luxurious interior designs and quiet operation.",
        specs: {
          drive: "Hydraulic Pumping Unit",
          capacity: "4 to 6 Passengers (up to 450kg)",
          stops: "Up to 4 floors standard",
        },
        specifications: {
          drive: "Hydraulic Pumping Unit",
          capacity: "4 to 6 Passengers (up to 450kg)",
          stops: "Up to 4 floors standard",
        },
        featured: true,
        productType: "elevator-kit",
        brand: "",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Smooth piston-driven travel", "No roof headroom requirements", "Ideal for bungalows and luxury villas"],
        displayOrder: 30,
      },
      {
        title: "High-Speed Passenger Lift Kit",
        slug: "high-speed-traction-kit",
        category: "elevator-kit",
        badge: "High-Rise Kit",
        badgeColor: "brand-orange",
        featuredImage: "/images/products/mrl-kit.png",
        images: ["/images/products/mrl-kit.png"],
        galleryImages: ["/images/products/mrl-kit.png"],
        shortDescription: "Complete high-speed traction elevator kit. Optimized for high-rise commercial offices and apartment blocks.",
        description: "A complete traction lift package engineered for heavy commercial use. Features advanced control dispatch, group control support, and absolute structural safety measures.",
        fullDescription: "A complete traction lift package engineered for heavy commercial use. Features advanced control dispatch, group control support, and absolute structural safety measures.",
        specs: {
          drive: "High-Capacity Gearless PM Motor",
          speed: "Up to 2.5 m/s",
          control: "Multi-elevator dispatching control",
        },
        specifications: {
          drive: "High-Capacity Gearless PM Motor",
          speed: "Up to 2.5 m/s",
          control: "Multi-elevator dispatching control",
        },
        featured: false,
        productType: "elevator-kit",
        brand: "",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Speeds up to 2.5 m/s supported", "Group control dispatching software", "Pre-wired plug-and-play traveling cable"],
        displayOrder: 31,
      },
      {
        title: "Stretcher Hospital Elevator Kit",
        slug: "hospital-stretcher-kit",
        category: "elevator-kit",
        badge: "Hospital Kit",
        badgeColor: "brand-blue",
        featuredImage: "/images/products/hydraulic-kit.png",
        images: ["/images/products/hydraulic-kit.png"],
        galleryImages: ["/images/products/hydraulic-kit.png"],
        shortDescription: "Complete stretcher elevator kit optimized for hospitals, emergency clinics, and elderly care centers.",
        description: "Engineered specifically to accommodate full-sized medical stretchers and support staff. Programmed with absolute leveling accuracy, smooth acceleration curves, and emergency backup power operations.",
        fullDescription: "Engineered specifically to accommodate full-sized medical stretchers and support staff. Programmed with absolute leveling accuracy, smooth acceleration curves, and emergency backup power operations.",
        specs: {
          cabinDepth: "2400mm deep stretch layout",
          leveling: "Direct leveling precision (±2mm)",
          control: "Emergency hospital priority service key",
        },
        specifications: {
          cabinDepth: "2400mm deep stretch layout",
          leveling: "Direct leveling precision (±2mm)",
          control: "Emergency hospital priority service key",
        },
        featured: false,
        productType: "elevator-kit",
        brand: "",
        subCategory: "",
        inquiryEnabled: true,
        highlights: ["Extra-deep stretcher cabin layout", "Highly precise leveling logic (±2mm)", "Emergency hospital override keys"],
        displayOrder: 32,
      }
    ];
    let seededCount = 0;
    for (const item of productsData) {
      const exists = await Product.findOne({ slug: item.slug });
      if (!exists) {
        await Product.create(item);
        seededCount++;
      }
    }
    console.log(`Product seeding complete. Created ${seededCount} new products. Existing products left untouched.`);
  } else {
    console.log("Products already exist. Skipping products seed.");
  }

  // 5. Seed Testimonials
  const testimonialsCount = await Testimonial.countDocuments();
  if (testimonialsCount === 0) {
    const testimonialsData = [
      {
        name: "Shadman Sheikh",
        role: "Managing Director",
        rating: 5,
        review: "Wonderful experience. They manufacture premium finishing doors, cabins and other elevator components. Mr. Chetan is doing a great job. The finishing of the products and the team of Shivshakti is mind blowing. Keep growing.",
        image: "",
        displayOrder: 0,
      },
      {
        name: "Kautuk Patel",
        role: "Designer",
        rating: 5,
        review: "One-roof solutions for all elevator products. Also authorized dealer for the world's No. 1 wire rope brand. Nice experience.",
        image: "",
        displayOrder: 1,
      },
      {
        name: "Dilip Barad",
        role: "Industry Professional",
        rating: 5,
        review: "The best quality product is delivered on time. Very nice work culture. Customer satisfaction, safety, and advanced technology are the main identity of Shivshakti.",
        image: "",
        displayOrder: 2,
      },
      {
        name: "Keyur Sharma",
        role: "Local Guide",
        rating: 5,
        review: "Manufacturing best quality products of elevator cabin, auto door, frame, IFD door and wire rope. Cabin delivered within 7 days. Auto door and frame dispatched same day of order.",
        image: "",
        displayOrder: 3,
      },
      {
        name: "Divyaraj Parmar",
        role: "Local Guide",
        rating: 5,
        review: "Everything is under one roof for elevator needs. Impressed by their own Shivshakti make auto doors. Great product quality and service.",
        image: "",
        displayOrder: 4,
      },
      {
        name: "Dinesh Batavia",
        role: "Local Guide",
        rating: 5,
        review: "Good manufacturer of elevators for all purposes. The unit has the latest equipment to produce quality products. Management is also good.",
        image: "",
        displayOrder: 5,
      },
    ];
    await Testimonial.insertMany(testimonialsData);
    console.log("Seeded default testimonials.");
  } else {
    console.log("Testimonials already exist. Skipping testimonials seed.");
  }

  console.log("Database seeded successfully!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seeding error:", err);
  process.exit(1);
});
