export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  SALES_MANAGER: "SALES_MANAGER",
  SALES_EXECUTIVE: "SALES_EXECUTIVE",
  CONTENT_EDITOR: "CONTENT_EDITOR",
  MARKETING_MANAGER: "MARKETING_MANAGER"
};

export const PERMISSIONS = {
  VIEW_CRM: "VIEW_CRM",
  EDIT_CRM: "EDIT_CRM",
  DELETE_CRM: "DELETE_CRM",
  EXPORT_CRM: "EXPORT_CRM",
  MANAGE_USERS: "MANAGE_USERS",
  VIEW_SETTINGS: "VIEW_SETTINGS",
  EDIT_SETTINGS: "EDIT_SETTINGS",
  MANAGE_PRODUCTS: "MANAGE_PRODUCTS",
  MANAGE_BLOGS: "MANAGE_BLOGS",
  MANAGE_EMAIL_TEMPLATES: "MANAGE_EMAIL_TEMPLATES",
  VIEW_ANALYTICS: "VIEW_ANALYTICS"
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.SALES_MANAGER]: [
    PERMISSIONS.VIEW_CRM,
    PERMISSIONS.EDIT_CRM,
    PERMISSIONS.EXPORT_CRM,
    PERMISSIONS.VIEW_ANALYTICS
  ],
  [ROLES.SALES_EXECUTIVE]: [
    PERMISSIONS.VIEW_CRM,
    PERMISSIONS.EDIT_CRM
  ],
  [ROLES.CONTENT_EDITOR]: [
    PERMISSIONS.MANAGE_BLOGS
  ],
  [ROLES.MARKETING_MANAGER]: [
    PERMISSIONS.MANAGE_EMAIL_TEMPLATES,
    PERMISSIONS.VIEW_ANALYTICS
  ]
};

export function getPermissionsByRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}
